@startuml
autoactivate on
hide footbox

box "Logic" #LightBlue
participant ":LogicManager" #3333C4
participant ":StateManager" #3333C4
participant ":AddressBookParser" #3333C4
participant ":DeleteCommandParser" #3333C4
participant "d:DeleteCommand" #3333C4
participant "p:ConfirmationPendingResult" #3333C4
participant "r:CommandResult" #3333C4
end box

box "Model" #FF0000
participant "m:Model" #9D0012
end box

-> ":LogicManager" #FFBBBB : execute("delete 1")

":LogicManager" -> ":LogicManager" #Red : buildCommand
":LogicManager" -> ":StateManager" : isAwaitingUserConfirmation
return false
":LogicManager" -> ":AddressBookParser" #Orange : parseCommand("delete 1")
create ":DeleteCommandParser"
":AddressBookParser" -> ":DeleteCommandParser" #Grey : parse("1")
create "d:DeleteCommand"
":DeleteCommandParser" -> "d:DeleteCommand" #Blue :
return d
return d
destroy ":DeleteCommandParser"
return d
return d
":LogicManager" -> "d:DeleteCommand" #Blue : execute(m)
create "p:ConfirmationPendingResult"
"d:DeleteCommand" -> "p:ConfirmationPendingResult" #C8C8FA :
return p
return p
destroy "d:DeleteCommand"
":LogicManager" -> ":LogicManager" #Red : saveIfRequired(p)
return
return commandResult

-> ":LogicManager" #FFBBBB : execute("y/n")

":LogicManager" -> ":LogicManager" #Red : buildCommand
":LogicManager" -> ":StateManager" : isAwaitingUserConfirmation
return true

alt "y"
    ":LogicManager" -> ":AddressBookParser" #Orange : parseConfirmationCommand("y")
return ConfirmCommand
":LogicManager" -> "p:ConfirmationPendingResult" #C8C8FA : execute(m)
"p:ConfirmationPendingResult" -> "m:Model" : deletePerson(1)
return
create "r:CommandResult"
"p:ConfirmationPendingResult" -> "r:CommandResult" :
return
return
destroy "p:ConfirmationPendingResult"

else "n"
    ":LogicManager" -> ":AddressBookParser" #Orange : parseConfirmationCommand("n")
return ConfirmCommand
":LogicManager" -> "p:ConfirmationPendingResult" #C8C8FA : execute(m)
create "r:CommandResult"
"p:ConfirmationPendingResult" -> "r:CommandResult"
return CommandResult
return
destroy "p:ConfirmationPendingResult"
end
return
return
@enduml
