@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
Class HiddenOutside2 #FFFFFF
HiddenOutside ..> Ui

UiManager ..|> Ui
UiManager --> "1" MainWindow
MainWindow *-->  "1" CommandBox
MainWindow *--> "1" ResultDisplay
MainWindow *--> "1" PersonListPanel
MainWindow *--> "1" StatusBarFooter

PersonListPanel --> "*" PersonCard

MainWindow --|> UiPart

ResultDisplay --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
CommandBox --|> UiPart

PersonCard ..> Model
PersonCard ..> Logic
UiManager --> Logic
MainWindow --> Logic


UiManager -> Model
CommandBox -> Model
@enduml
